딥러닝 기초 스터디 / 박찬영

# 📌 10.1. 임베딩

☑️ ****10.1.1. 희소 표현 기반 임베딩****

In [ ]:
from google.colab import drive
drive.mount("/content/drive")

import os
os.chdir("drive/MyDrive/2025-1 프로메테우스 스터디")

import pandas as pd
import numpy as np
class2 = pd.read_csv("chap10/data/class2.csv")

from sklearn import preprocessing
label_encoder = preprocessing.LabelEncoder()  # 데이터 인코딩
onehot_encoder = preprocessing.OneHotEncoder()  # 데이터를 숫자 형식으로 표현

train_x = label_encoder.fit_transform(class2['class2'])
print(train_x)
train_x = onehot_encoder.fit_transform(np.array(class2['class2']).reshape(-1, 1)).toarray()
print(train_x)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
[2 2 1 0 1 0]
[[0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]]


☑️ **10.1.2. 횟수 기반 임베딩**

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
corpus = [
    'This is last chance.',
    'and if you do not have this chance.',
    'you will never get any chance.',
    'will you do get this one?',
    'please, get this chance',
]

vect = CountVectorizer()
vect.fit(corpus)
print(vect.vocabulary_)

vect.transform(['you will never get any chance.']).toarray()

{'this': 13, 'is': 7, 'last': 8, 'chance': 2, 'and': 0, 'if': 6, 'you': 15, 'do': 3, 'not': 10, 'have': 5, 'will': 14, 'never': 9, 'get': 4, 'any': 1, 'one': 11, 'please': 12}


array([[0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1]])

In [ ]:
vect = CountVectorizer(stop_words=["and", "is", "please", "this"]).fit(corpus)
print(vect.vocabulary_)

{'last': 6, 'chance': 1, 'if': 5, 'you': 11, 'do': 2, 'not': 8, 'have': 4, 'will': 10, 'never': 7, 'get': 3, 'any': 0, 'one': 9}


In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
doc = ['I like machine learning', 'I love deep learning', 'I run everyday']

tfidf_vectorizer = TfidfVectorizer(min_df=1)
tfidf_matrix = tfidf_vectorizer.fit_transform(doc)
print(tfidf_matrix.toarray())
print()

doc_distance = (tfidf_matrix * tfidf_matrix.T)
print('유사도를 위한', str(doc_distance.get_shape()[0]), 'x', str(doc_distance.get_shape()[1]), '행렬을 만들었습니다.')
print(doc_distance.toarray())

[[0.         0.         0.4736296  0.62276601 0.         0.62276601
  0.        ]
 [0.62276601 0.         0.4736296  0.         0.62276601 0.
  0.        ]
 [0.         0.70710678 0.         0.         0.         0.
  0.70710678]]

유사도를 위한 3 x 3 행렬을 만들었습니다.
[[1.       0.224325 0.      ]
 [0.224325 1.       0.      ]
 [0.       0.       1.      ]]


☑️ **10.1.3. 예측 기반 임베딩**

In [ ]:
!pip install gensim

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.0/61.0 kB 4.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.6/60.6 kB 4.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 26.7/26.7 MB 87.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.3/18.3 MB 118.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 38.6/38.6 MB 22.7 MB/s eta 0:00:00
  Attempting uninstall: numpy
    Found existing installation: numpy 2.0.2
    Uninstalling numpy-2.0.2:
      Successfully uninstalled numpy-2.0.2
  Attempting uninstall: scipy
    Found existing installation: scipy 1.15.2
    Uninstalling scipy-1.15.2:
      Successfully uninstalled scipy-1.15.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
thinc 8.3.6 requires numpy<3.0.0,>=2.0.0, but you have numpy 1.26.4 which is incompatible.


In [ ]:
import nltk
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.


True

In [ ]:
from nltk.tokenize import sent_tokenize, word_tokenize
import warnings
warnings.filterwarnings(action='ignore')
import gensim
from gensim.models import Word2Vec

sample = open("chap10/data/peter.txt", "r", encoding='UTF8')  # 데이터셋 로딩
s = sample.read()

f = s.replace("\n", " ")
data = []

for i in sent_tokenize(f):  # 문장마다 반복
    temp = []
    for j in word_tokenize(i):  # 문장을 단어로 토큰화
        temp.append(j.lower())  # 토큰화된 단어를 소문자로 변환하여 temp에 저장
    data.append(temp)

print(data)

[['once', 'upon', 'a', 'time', 'in', 'london', ',', 'the', 'darlings', 'went', 'out', 'to', 'a', 'dinner', 'party', 'leaving', 'their', 'three', 'children', 'wendy', ',', 'jhon', ',', 'and', 'michael', 'at', 'home', '.'], ['after', 'wendy', 'had', 'tucked', 'her', 'younger', 'brothers', 'jhon', 'and', 'michael', 'to', 'bed', ',', 'she', 'went', 'to', 'read', 'a', 'book', '.'], ['she', 'heard', 'a', 'boy', 'sobbing', 'outside', 'her', 'window', '.'], ['he', 'was', 'flying', '.'], ['there', 'was', 'little', 'fairy', 'fluttering', 'around', 'him', '.'], ['wendy', 'opened', 'the', 'window', 'to', 'talk', 'to', 'him', '.'], ['“', 'hello', '!'], ['who', 'are', 'you', '?'], ['why', 'are', 'you', 'crying', '”', ',', 'wendy', 'asked', 'him', '.'], ['“', 'my', 'name', 'is', 'peter', 'pan', '.'], ['my', 'shadow', 'wouldn', '’', 't', 'stock', 'to', 'me.', '”', ',', 'he', 'replied', '.'], ['she', 'asked', 'him', 'to', 'come', 'in', '.'], ['peter', 'agreed', 'and', 'came', 'inside', 'the', 'room', '

In [ ]:
model1 = gensim.models.Word2Vec(data, min_count=1, vector_size=100, window=5, sg=0)

print("Cosine similarity between 'peter' " + "'wendy' - CBOW : ",
      model1.wv.similarity('peter', 'wendy'))
print("Cosine similarity between 'peter' " + "'hook' - CBOW : ",
      model1.wv.similarity('peter', 'hook'))

Cosine similarity between 'peter' 'wendy' - CBOW :  0.074393824
Cosine similarity between 'peter' 'hook' - CBOW :  0.027709836


In [ ]:
model2 = gensim.models.Word2Vec(data, min_count=1, vector_size=100, window=5, sg=1)

print("Cosine similarity between 'peter' " + "'wendy' - Skip Gram : ",
      model2.wv.similarity('peter', 'wendy'))
print("Cosine similarity between 'peter' " + "'hook' - Skip Gram : ",
      model2.wv.similarity('peter', 'hook'))

Cosine similarity between 'peter' 'wendy' - Skip Gram :  0.40088683
Cosine similarity between 'peter' 'hook' - Skip Gram :  0.5201673


In [ ]:
from gensim.test.utils import common_texts
from gensim.models import FastText

model = FastText('chap10/data/peter.txt', vector_size=4, window=3, min_count=1, epochs=10)
sim_score = model.wv.similarity('peter', 'wendy')
print(sim_score)
sim_score = model.wv.similarity('peter', 'hook')
print(sim_score)

0.4592452
0.043825686


In [ ]:
from __future__ import print_function
from gensim.models import KeyedVectors

model_kr = KeyedVectors.load_word2vec_format('chap10/data/wiki.ko.vec')

find_similar_to = '노력'

for similar_word in model_kr.similar_by_word(find_similar_to):
    print("Word: {0}, Similarity: {1:.2f}".format(
        similar_word[0], similar_word[1]
    ))

similarities = model_kr.most_similar(positive=['동물', '육식동물'], negative=['사람'])
print(similarities)

☑️ **10.1.4. 횟수/예측 기반 임베딩**

In [ ]:
import numpy as np
%matplotlib notebook
import matplotlib.pyplot as plt
plt.style.use('ggplot')
from sklearn.decomposition import PCA
from gensim.test.utils import datapath, get_tmpfile
from gensim.models import KeyedVectors
from gensim.scripts.glove2word2vec import glove2word2vec

glove_file = datapath('chap10/data/glove.6B.100d.txt')
word2vec_glove_file = get_tmpfile("glove.6B.100d.word2vec.txt")  # 워드투벡터 형태로 변환
glove2word2vec(glove_file, word2vec_glove_file)

model = KeyedVectors.load_word2vec_format(word2vec_glove_file)
model.most_similar('bill')  # 가장 유사한 단어들의 리스트

model.most_similar('cherry')  # 가장 유사한 단어들의 리스트

# woman, king과 유사성이 높으면서 man과 관련성이 없는 단어
result = model.most_similar(positive=['woman', 'king'], negative=['man'])
print("{}: {:.4f}".format(*result[0]))

In [ ]:
def analogy(x1, x2, y1):
    result = model.most_similar(positive=[y1, x2], negative=[x1])
    return result[0][0]
analogy('australia', 'beer', 'france')
analogy('tall', 'tallest', 'long')
print(model.doesnt_match("breakfast cereal dinner lunch".split()))  # 유사도가 가장 낮은 단어 반환